server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.154.201:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # 清理
    #lease-renewal-interval-in-seconds: 30
    #lease-expiration-duration-in-seconds: 90

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.liangliang.springcloud.entity




