server:
  port: 8004

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.154.201
      port: 8500
      discovery:
        hostname: 192.168.154.201
        service-name: ${spring.application.name}
