server:
  port: 8801

spring:
  application:
    name: stream-rabbitmq-provider
  rabbitmq:
    host: 192.168.154.201
    port: 5672
    username: root
    password: root
  cloud:
    stream:
      binders:
        output:
          destination: myExchanges
          binder: defaultRabbit

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: rabbitmq-provider8801
    prefer-ip-address: true
