server:
  port: 9002

spring:
  application:
    name: nacos-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.154.201:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

