server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment-route1
        #uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/getPaymentById/**, /discovery/getInfo, /payment/hystrixTest




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true

